apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-0axk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-0axk
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-0axk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-0axk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-0axk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pajq-tenant/status-quarkus-io/statusquarkusio-0axk@sha256:33202d9f54a82e8b7c920f6b33971148a05d9ebc81c3fd6a66d0111e091e3f96
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
